package Modelos;

public enum Moeda {
    AED("AED", "Dirham dos Emirados Árabes Unidos", "Emirados Árabes Unidos"),
    AFN("AFN", "Afghani Afegão", "Afeganistão"),
    ALL("ALL", "Lek da Albânia", "Albânia"),
    AMD("AMD", "Dram armênio", "Armênia"),
    ANG("ANG", "Guilder holandês antillian", "Antilhas Holandesas"),
    AOA("AOA", "Kwanza de Angola", "Angola"),
    ARS("ARS", "Peso argentino", "Argentina"),
    AUD("AUD", "Dólar australiano", "Austrália"),
    AWG("AWG", "Florim de Aruba", "Aruba"),
    AZN("AZN", "Manat do Azerbaijão", "Azerbaijão"),
    BAM("BAM", "Bósnia e Herzegovina Mark", "Bósnia e Herzegovina"),
    BBD("BBD", "Dólar de Barbados", "Barbados"),
    BDT("BDT", "Bangladeshi Taka", "Bangladesh"),
    BGN("BGN", "Lev da Bulgária", "Bulgária"),
    BHD("BHD", "Dinar do Bahrein", "Bahrein"),
    BIF("BIF", "Franco do Burundi", "Burundi"),
    BMD("BMD", "Dólar de Bermudas", "Bermudas"),
    BND("BND", "Dólar de Brunei", "Brunei"),
    BOB("BOB", "Boliviano Boliviano", "Bolívia"),
    BRL("BRL", "Real Brasileiro", "Brasil"),
    BSD("BSD", "Dólar das Bahamas", "Bahamas"),
    BTN("BTN", "Ngultrum do Butão", "Butão"),
    BWP("BWP", "Botswana Pula", "Botsuana"),
    BYN("BYN", "Rublo bielorrusso", "Bielorrússia"),
    BZD("BZD", "Dólar de Belize", "Belize"),
    CAD("CAD", "Dólar canadense", "Canadá"),
    CDF("CDF", "Franco congolês", "República Democrática do Congo"),
    CHF("CHF", "Franco suíço", "Suíça"),
    CLP("CLP", "Peso do Chile", "Chile"),
    CNY("CNY", "Renminbi chinês", "China"),
    COP("COP", "Peso colombiano", "Colômbia"),
    CRC("CRC", "Colón da Costa Rica", "Costa Rica"),
    CUP("CUP", "Peso cubano", "Cuba"),
    CVE("CVE", "Escudo de Cabo Verde", "Cabo Verde"),
    CZK("CZK", "Coroa checa", "República Tcheca"),
    DJF("DJF", "Franco de Djibouti", "Djibouti"),
    DKK("DKK", "Coroa dinamarquesa", "Dinamarca"),
    DOP("DOP", "Peso dominicano", "República Dominicana"),
    DZD("DZD", "Dinar argelino", "Argélia"),
    EGP("EGP", "Libra egípcia", "Egito"),
    ERN("ERN", "Nakfa da Eritreia", "Eritreia"),
    ETB("ETB", "Birr etíope", "Etiópia"),
    EUR("EUR", "Euro", "União Europeia"),
    FJD("FJD", "Dólar de Fiji", "Fiji"),
    FKP("FKP", "Libra das Ilhas Falkland", "Ilhas Falkland"),
    FOK("FOK", "Króna das Ilhas Faroé", "Ilhas Faroé"),
    GBP("GBP", "Libra esterlina", "Reino Unido"),
    GEL("GEL", "Lari da Geórgia", "Geórgia"),
    GGP("GGP", "Libra de Guernsey", "Guernsey"),
    GHS("GHS", "Cedi do Gana", "Gana"),
    GIP("GIP", "Libra de Gibraltar", "Gibraltar"),
    GMD("GMD", "Dalasi da Gâmbia", "Gâmbia"),
    GNF("GNF", "Franco da Guiné", "Guiné"),
    GTQ("GTQ", "Quetzal da Guatemala", "Guatemala"),
    GYD("GYD", "Dólar da Guiana", "Guiana"),
    HKD("HKD", "Dólar de Hong Kong", "Hong Kong"),
    HNL("HNL", "Lempira de Honduras", "Honduras"),
    HRK("HRK", "Kuna da Croácia", "Croácia"),
    HTG("HTG", "Gourde haitiano", "Haiti"),
    HUF("HUF", "Forint húngaro", "Hungria"),
    IDR("IDR", "Rupiah da Indonésia", "Indonésia"),
    ILS("ILS", "Novo shekel de Israel", "Israel"),
    IMP("IMP", "Libra da Ilha de Man", "Ilha de Man"),
    INR("INR", "Rúpia indiana", "Índia"),
    IQD("IQD", "Dinar iraquiano", "Iraque"),
    IRR("IRR", "Rial do Irã", "Irã"),
    ISK("ISK", "Króna da Islândia", "Islândia"),
    JEP("JEP", "Libra de Jersey", "Jersey"),
    JMD("JMD", "Dólar jamaicano", "Jamaica"),
    JOD("JOD", "Dinar jordaniano", "Jordânia"),
    JPY("JPY", "Yen japonês", "Japão"),
    KES("KES", "Shilling queniano", "Quênia"),
    KGS("KGS", "Som do Quirguistão", "Quirguistão"),
    KHR("KHR", "Riel do Camboja", "Camboja"),
    KID("KID", "Dólar de Kiribati", "Kiribati"),
    KMF("KMF", "Franco das Comores", "Comores"),
    KRW("KRW", "Won sul-coreano", "Coreia do Sul"),
    KWD("KWD", "Dinar do Kuwait", "Kuwait"),
    KYD("KYD", "Dólar das Ilhas Cayman", "Ilhas Cayman"),
    KZT("KZT", "Tenge do Cazaquistão", "Cazaquistão"),
    LAK("LAK", "Kip do Laos", "Laos"),
    LBP("LBP", "Libra libanesa", "Líbano"),
    LKR("LKR", "Rúpia do Sri Lanka", "Sri Lanka"),
    LRD("LRD", "Dólar da Libéria", "Libéria"),
    LSL("LSL", "Loti do Lesoto", "Lesoto"),
    LYD("LYD", "Dinar da Líbia", "Líbia"),
    MAD("MAD", "Dirham marroquino", "Marrocos"),
    MDL("MDL", "Leu da Moldávia", "Moldávia"),
    MGA("MGA", "Ariary malgaxe", "Madagáscar"),
    MKD("MKD", "Denar macedônio", "Macedônia do Norte"),
    MMK("MMK", "Kyat de Mianmar", "Mianmar"),
    MNT("MNT", "Tugrik da Mongólia", "Mongólia"),
    MOP("MOP", "Pataca macaense", "Macau"),
    MRU("MRU", "Ouguiya da Mauritânia", "Mauritânia"),
    MUR("MUR", "Rúpia das Maurícias", "Maurício"),
    MVR("MVR", "Rufiyaa das Maldivas", "Maldivas"),
    MWK("MWK", "Kwacha do Malaui", "Malaui"),
    MXN("MXN", "Peso mexicano", "México"),
    MYR("MYR", "Ringgit da Malásia", "Malásia"),
    MZN("MZN", "Metical de Moçambique", "Moçambique"),
    NAD("NAD", "Dólar da Namíbia", "Namíbia"),
    NGN("NGN", "Naira da Nigéria", "Nigéria"),
    NIO("NIO", "Córdoba da Nicarágua", "Nicarágua"),
    NOK("NOK", "Coroa norueguesa", "Noruega"),
    NPR("NPR", "Rúpia nepalesa", "Nepal"),
    NZD("NZD", "Dólar da Nova Zelândia", "Nova Zelândia"),
    OMR("OMR", "Rial do Omã", "Omã"),
    PAB("PAB", "Balboa do Panamá", "Panamá"),
    PEN("PEN", "Sol peruano", "Peru"),
    PGK("PGK", "Kina de Papua Nova Guiné", "Papua Nova Guiné"),
    PHP("PHP", "Peso filipino", "Filipinas"),
    PKR("PKR", "Rúpia do Paquistão", "Paquistão"),
    PLN("PLN", "Zloty polonês", "Polônia"),
    PYG("PYG", "Guarani paraguaio", "Paraguai"),
    QAR("QAR", "Rial do Qatar", "Catar"),
    RON("RON", "Leu romeno", "Romênia"),
    RSD("RSD", "Dinar sérvio", "Sérvia"),
    RUB("RUB", "Rublo russo", "Rússia"),
    RWF("RWF", "Franco ruandês", "Ruanda"),
    SAR("SAR", "Rial saudita", "Arábia Saudita"),
    SBD("SBD", "Dólar das Ilhas Salomão", "Ilhas Salomão"),
    SCR("SCR", "Rúpia de Seychelles", "Seychelles"),
    SDG("SDG", "Libra do Sudão", "Sudão"),
    SEK("SEK", "Coroa sueca", "Suécia"),
    SGD("SGD", "Dólar de Singapura", "Singapura"),
    SHP("SHP", "Libra de Santa Helena", "Santa Helena"),
    SLE("SLE", "Leone de Serra Leoa", "Serra Leoa"),
    SOS("SOS", "Shilling somali", "Somália"),
    SRD("SRD", "Dólar do Suriname", "Suriname"),
    SSP("SSP", "Libra do Sudão do Sul", "Sudão do Sul"),
    STN("STN", "Dobra de São Tomé e Príncipe", "São Tomé e Príncipe"),
    SYP("SYP", "Libra síria", "Síria"),
    SZL("SZL", "Lilangeni de Essuatíni", "Essuatíni"),
    THB("THB", "Baht tailandês", "Tailândia"),
    TJS("TJS", "Somoni do Tajiquistão", "Tajiquistão"),
    TMT("TMT", "Manat do Turcomenistão", "Turcomenistão"),
    TND("TND", "Dinar tunisiano", "Tunísia"),
    TOP("TOP", "Pa'anga de Tonga", "Tonga"),
    TRY("TRY", "Lira turca", "Turquia"),
    TTD("TTD", "Dólar de Trinidad e Tobago", "Trinidad e Tobago"),
    TVD("TVD", "Dólar de Tuvalu", "Tuvalu"),
    TWD("TWD", "Novo dólar taiwanês", "Taiwan"),
    TZS("TZS", "Shilling da Tanzânia", "Tanzânia"),
    UAH("UAH", "Hryvnia ucraniana", "Ucrânia"),
    UGX("UGX", "Shilling de Uganda", "Uganda"),
    USD("USD", "Dólar dos Estados Unidos", "Estados Unidos"),
    UYU("UYU", "Peso uruguaio", "Uruguai"),
    UZS("UZS", "Som uzbeque", "Uzbequistão"),
    VES("VES", "Bolívar soberano da Venezuela", "Venezuela"),
    VND("VND", "Dong vietnamita", "Vietnã"),
    VUV("VUV", "Vatu de Vanuatu", "Vanuatu"),
    WST("WST", "Tala samoano", "Samoa"),
    XAF("XAF", "Franco CFA da África Central", "África Central"),
    XCD("XCD", "Dólar do Caribe Oriental", "Caribe Oriental"),
    XDR("XDR", "Direitos especiais de saque", "Internacional"),
    XOF("XOF", "Franco CFA da África Ocidental", "África Ocidental"),
    XPF("XPF", "Franco CFP", "Pacífico Francês"),
    YER("YER", "Rial iemenita", "Iémen"),
    ZAR("ZAR", "Rand sul-africano", "África do Sul"),
    ZMW("ZMW", "Kwacha da Zâmbia", "Zâmbia"),
    ZWL("ZWL", "Dólar do Zimbábue", "Zimbábue");

    private final String codigoMoeda;
    private final String nomeMoeda;
    private final String paisMoeda;

    Moeda(String codigoMoeda, String nomeMoeda, String paisMoeda) {
        this.codigoMoeda = codigoMoeda;
        this.nomeMoeda = nomeMoeda;
        this.paisMoeda = paisMoeda;
    }



    public String getCodigoMoeda() {
        return codigoMoeda;
    }

    public String getNomeMoeda() {
        return nomeMoeda;
    }

    public String getPaisMoeda() {
        return paisMoeda;
    }


    @Override
    public String toString() {
        return String.format("\n\tCodigo da Moeda: %s\n\tNome da Moeda: %s\n\tPais da Moeda: %s\n",
                ConsoleColors.BLACK_BACKGROUND + getCodigoMoeda() + ConsoleColors.RESET,
                ConsoleColors.BLACK_BACKGROUND + getNomeMoeda() + ConsoleColors.RESET,
                ConsoleColors.BLACK_BACKGROUND + getPaisMoeda() + ConsoleColors.RESET
        );
    }
}
